name: Performance Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  performance-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run performance tests
        run: |
          docker compose -f docker-compose.performance.yaml up --build -d
          sleep 10  # Wait for the app to be ready
          docker compose -f docker-compose.performance.yaml run k6 > performance-results.txt
          docker compose -f docker-compose.performance.yaml down

      - name: Display threshold results
        run: |
          cat performance-results.txt | grep -A 30 "THRESHOLDS"

      - name: Upload performance results
        uses: actions/upload-artifact@v4
        with:
          name: performance-results
          path: |
            performance-results.txt
            test_performance/performance-report.html
